### ISSUE TITLE
Add a new button "More Themes..." on Style Configurator

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/nppThemes#5]
Add a new button "More Themes..." on Style Configurator, beside of theme selector (combobox) for opening [nppThemes](https://github.com/notepad-plus-plus/nppThemes) in a browser.

**Comment by pryrt** [comment]
If you want to leave it here, that's fine, but I would think this issue should be in the application issues list, not the nppThemes issues, because it requires a change to the codebase.

**Comment by donho** [comment]
OK, I will close it for the moment.
Once there are more theme I will add the button.
